version: '3.1'

services:
  mysql:
    image: mysql:5.7
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - 3306:3306
    network_mode: default

